resolver: lts-13.20
packages:
- .
- ./source/tct-core
- ./source/tct-common
- ./source/tct-trs
- ./source/tct-its
extra-deps:
- fgl-visualize-0.1.0.1
- graphviz-2999.20.0.3
- term-rewriting-0.4.0.1
- union-find-array-0.1.0.2
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-xml
  commit: 0030d67be24e8ba424869d9e3fc9f66c1a8627be
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-ext
  commit: 79296ce047501c13bb1e5d8605b8ee6d2e63be7d
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-applicative
  commit: 945ca308b33a650795d9238c7d779e22641f5509
- git: https://github.com/ComputationWithBoundedResources/hoca
  commit: f4910694dd454f647af8c83741ab49952b827dec
- git: https://github.com/ComputationWithBoundedResources/ara-inference
  commit: 49a9700fe78d2dce0ff016c35c41dcbeb78cb11b
- git: https://github.com/ComputationWithBoundedResources/slogic
  commit: 1cb609cb7fac1cba186969da90157ad7d0caeeac
