resolver: lts-13.20
packages:
- .
- ./source/tct-core
- ./source/tct-common
- ./source/tct-trs
- ./source/tct-its
extra-deps:
- fgl-visualize-0.1.0.1
- graphviz-2999.20.0.3
- term-rewriting-0.4.0.1
- union-find-array-0.1.0.2
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-xml
  commit: 0030d67be24e8ba424869d9e3fc9f66c1a8627be
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-ext
  commit: 79296ce047501c13bb1e5d8605b8ee6d2e63be7d
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-applicative
  commit: 945ca308b33a650795d9238c7d779e22641f5509
- git: https://github.com/ComputationWithBoundedResources/hoca
  commit: f4910694dd454f647af8c83741ab49952b827dec
- git: https://github.com/ComputationWithBoundedResources/ara-inference
  commit: 49a9700fe78d2dce0ff016c35c41dcbeb78cb11b
- git: https://github.com/ComputationWithBoundedResources/slogic
  commit: 1cb609cb7fac1cba186969da90157ad7d0caeeac
#- git: https://github.com/ComputationWithBoundedResources/tct-common
#  commit: 7dda9e986887cc45b922f7834e324517cc3d6d2f
#- git: https://github.com/ComputationWithBoundedResources/tct-core
#  commit: ea34d9af0a3a571f8d013d6d1e663c8f87b7f7e1
- git: https://github.com/ComputationWithBoundedResources/tct-hoca
  commit: 69526441ed25bbde392b9cf11073310c4ab25f69
#- git: https://github.com/ComputationWithBoundedResources/tct-its
#commit: 19de61bd2470df0fd43a27cc45fd963415d0d385

- git: https://github.com/ComputationWithBoundedResources/lare
  commit: 02d89b97d57e3a3697727e29786c56564c296fff
- git: https://github.com/ComputationWithBoundedResources/paicc
  commit: aca2a54f01d9b7118fecf91be429cae60a51d313

- set-monad-0.3.0.0
- git: https://github.com/ComputationWithBoundedResources/tct-jbc
  commit: 36b44e66ea389ff3653f4d49da6feff67471102c
- git: https://github.com/ComputationWithBoundedResources/jat
  commit: b73c93375a36eb6ccfd688fb82719dff46a1e514

